services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: jupyter
        USER_UID: 1011
        USER_GID: 1011
    container_name: jupyter-py-r
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace

