services:
  jupyter:
    image: tbrown122387/stat-1602:latest
    container_name: jupyter-datascience
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    # Optionally set resource limits
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

# Optional: Create named volumes for persistent storage
volumes:
  jupyter_data:
    driver: local
