name: Build and Push Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [stat-1602, stat-5430]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.folder }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:latest

